// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mock_tracker_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	tracker "LoflyBE/internal/tracker"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockITrackerService is a mock of ITrackerService interface.
type MockITrackerService struct {
	ctrl     *gomock.Controller
	recorder *MockITrackerServiceMockRecorder
	isgomock struct{}
}

// MockITrackerServiceMockRecorder is the mock recorder for MockITrackerService.
type MockITrackerServiceMockRecorder struct {
	mock *MockITrackerService
}

// NewMockITrackerService creates a new mock instance.
func NewMockITrackerService(ctrl *gomock.Controller) *MockITrackerService {
	mock := &MockITrackerService{ctrl: ctrl}
	mock.recorder = &MockITrackerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITrackerService) EXPECT() *MockITrackerServiceMockRecorder {
	return m.recorder
}

// CreateTrackedFlight mocks base method.
func (m *MockITrackerService) CreateTrackedFlight(input tracker.CreateTrackedFlightRequest) (*tracker.TrackedFlight, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTrackedFlight", input)
	ret0, _ := ret[0].(*tracker.TrackedFlight)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTrackedFlight indicates an expected call of CreateTrackedFlight.
func (mr *MockITrackerServiceMockRecorder) CreateTrackedFlight(input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTrackedFlight", reflect.TypeOf((*MockITrackerService)(nil).CreateTrackedFlight), input)
}
