// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mocks/mock_tracker_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	tracker "LoflyBE/internal/tracker"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockITrackerRepo is a mock of ITrackerRepo interface.
type MockITrackerRepo struct {
	ctrl     *gomock.Controller
	recorder *MockITrackerRepoMockRecorder
	isgomock struct{}
}

// MockITrackerRepoMockRecorder is the mock recorder for MockITrackerRepo.
type MockITrackerRepoMockRecorder struct {
	mock *MockITrackerRepo
}

// NewMockITrackerRepo creates a new mock instance.
func NewMockITrackerRepo(ctrl *gomock.Controller) *MockITrackerRepo {
	mock := &MockITrackerRepo{ctrl: ctrl}
	mock.recorder = &MockITrackerRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITrackerRepo) EXPECT() *MockITrackerRepoMockRecorder {
	return m.recorder
}

// CreateTrackedFlight mocks base method.
func (m *MockITrackerRepo) CreateTrackedFlight(trackedFlight tracker.TrackedFlight) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTrackedFlight", trackedFlight)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTrackedFlight indicates an expected call of CreateTrackedFlight.
func (mr *MockITrackerRepoMockRecorder) CreateTrackedFlight(trackedFlight any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTrackedFlight", reflect.TypeOf((*MockITrackerRepo)(nil).CreateTrackedFlight), trackedFlight)
}

// DeleteTrackedFlight mocks base method.
func (m *MockITrackerRepo) DeleteTrackedFlight(id string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTrackedFlight", id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTrackedFlight indicates an expected call of DeleteTrackedFlight.
func (mr *MockITrackerRepoMockRecorder) DeleteTrackedFlight(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTrackedFlight", reflect.TypeOf((*MockITrackerRepo)(nil).DeleteTrackedFlight), id)
}

// GetTrackedFlight mocks base method.
func (m *MockITrackerRepo) GetTrackedFlight(id string) (*tracker.TrackedFlight, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrackedFlight", id)
	ret0, _ := ret[0].(*tracker.TrackedFlight)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrackedFlight indicates an expected call of GetTrackedFlight.
func (mr *MockITrackerRepoMockRecorder) GetTrackedFlight(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrackedFlight", reflect.TypeOf((*MockITrackerRepo)(nil).GetTrackedFlight), id)
}

// ListTrackedFlights mocks base method.
func (m *MockITrackerRepo) ListTrackedFlights() ([]tracker.TrackedFlight, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTrackedFlights")
	ret0, _ := ret[0].([]tracker.TrackedFlight)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTrackedFlights indicates an expected call of ListTrackedFlights.
func (mr *MockITrackerRepoMockRecorder) ListTrackedFlights() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTrackedFlights", reflect.TypeOf((*MockITrackerRepo)(nil).ListTrackedFlights))
}

// UpdateTrackedFlight mocks base method.
func (m *MockITrackerRepo) UpdateTrackedFlight(trackedFlight tracker.TrackedFlight) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTrackedFlight", trackedFlight)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTrackedFlight indicates an expected call of UpdateTrackedFlight.
func (mr *MockITrackerRepoMockRecorder) UpdateTrackedFlight(trackedFlight any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTrackedFlight", reflect.TypeOf((*MockITrackerRepo)(nil).UpdateTrackedFlight), trackedFlight)
}
